launch
read
approach OrbitalMall
dock
status
trades
accept wafer cones
launch
cargo
bay red
plot course to Mars
engage
approach Mars
describe Owl23
land ProjectX at Nicosia
people
planets
launch
plot course to Venus
engage
approach UnionServices
dock
give wafer cones
read
launch
plot course to Earth
engage
approach OrbitalMall
dock
accept Horus Eye
people
launch
approach Earth
land
contact Nordstrum
meet Nordstrum
describe Owl23
