launch
read
dock ProjectX with OrbitalMall
load wafer cones
launch
plot course to Mars
engage
land ProjectX at Nicosia
people
planets
launch
plot course to Venus
engage
people
dock ProjectX with UnionHall
services
unload wafer cones
services
undock
people
plot course to Earth
engage
approach OrbitalMall
dock
accept Horus Eye
people
launch
approach Earth
land
contact Nordstrum
meet Nordstrum
describe Owl23
